### ISSUE TITLE
Make clear what the difference between an index and a parameter for a type is

### ISSUE THREAD

**Issue by markuspf** [idris-lang/idris-tutorial#11]
Point being that they are not really different, but the tutorial mentions both and doesn't qualify what the difference is.

**Comment by jfdm** [comment]
Just to inform you that we are deprecating this version of the effects tutorial for a sphinx based solution that is to be hosted on the main Idris repository: https://www.github.com/idris-lang/idris-dev/ 

If your issue still exists in the new version can you please resubmit your issue to the main idris issue tracker.
