### ISSUE TITLE
Ordering and parameters blocks

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/idris-tutorial#37]
The user shaleh on Reddit pointed out that section 5.3 on `parameters` blocks doesn't explicitly state that the new parameters come before the ones specified on each definition.

**Comment by jfdm** [comment]
Just to inform you that we are deprecating this version of the tutorial for a sphinx based solution that is to be hosted on the main Idris repository: https://www.github.com/idris-lang/idris-dev/ 

If your issue still exists in the new version can you please resubmit your issue to the main idris issue tracker.
