### ISSUE TITLE
Tutorial lists "return" as a "Monad" method

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/idris-tutorial#38]
See https://github.com/idris-lang/Idris-dev/issues/1503#issuecomment-53999162

**Comment by jfdm** [comment]
Just to inform you that we are deprecating this version of the tutorial for a sphinx based solution that is to be hosted on the main Idris repository: https://www.github.com/idris-lang/idris-dev/

This new version allows for generation of ePub, PDF, and HTML versions that are publicly available using readthedocs.

I am marking this issue as being closed.
