### ISSUE TITLE
Missing quantification in code sample

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/idris-tutorial#39]
See https://github.com/idris-lang/Idris-dev/issues/1502 where the following was reported:

-----------------------

It seems there's an error on the code example in 3.8.3 / Dependent Pairs:
```
data Exists : (A : Type) -> (P : A -> Type) -> Type where
    Ex_intro : {P : A -> Type} -> (a : A) -> P a -> Exists A P
```

has error:

```
When elaborating type of Main.Ex_intro:
No such variable A
```

I think it should be:

```
data Exists : (A : Type) -> (P : A -> Type) -> Type where
    Ex_intro : {A : Type} -> {P : A -> Type} -> (a : A) -> P a -> Exists A P
```

**Comment by jfdm** [comment]
Just to inform you that we are deprecating this version of the tutorial for a sphinx based solution that is to be hosted on the main Idris repository: https://www.github.com/idris-lang/idris-dev/

If your issue still exists in the new version can you please resubmit your issue to the main idris issue tracker.
