### ISSUE TITLE
Repl help display outdated

### ISSUE THREAD

**Issue by LeifW** [idris-lang/idris-tutorial#51]
Here:
https://github.com/idris-lang/idris-tutorial/blob/master/content/starting.tex#L75-108
Specifically, the :js / :javascript command no longer exists.
In its place, you can use `:compile <codegen> <filename>`.

**Comment by jfdm** [comment]
Just to inform you that we are deprecating this version of the effects tutorial for a sphinx based solution that is to be hosted on the main Idris repository: https://www.github.com/idris-lang/idris-dev/ 

If your issue still exists in the new version can you please resubmit your issue to the main idris issue tracker.
