### ISSUE TITLE
Add ePub/.mobi/HTML versions

### ISSUE THREAD

**Issue by eallik** [idris-lang/idris-tutorial#53]
It would be immensely useful to have even at least one of those available out of the box without having to clone the repo (or a fork really) and figure out a way to build it. PDF's aren't particularly nice for on-screen reading!

**Comment by akamch** [comment]
[HTML](http://akamch.github.io/idris-tutorial/idris-tutorial.html), [EPUB](http://akamch.github.io/idris-tutorial/idris-tutorial.epub). Repo at https://github.com/akamch/idris-tutorial.

**Comment by eallik** [comment]
I know, I'm already using your ePub :)

**Comment by akamch** [comment]
:beers: I didn't quite catch the meaning of "out of the box" than.

No, I haven't, the process is not particularly interesting. Conversion can hardly be fully automated. I used pandoc to convert LaTeX to AsciiDoc with a healthy dose of sed at every step, added bibliography, tweaked some more.

**Comment by jfdm** [comment]
Just to inform you that we are deprecating this version of the effects tutorial for a sphinx based solution that is to be hosted on the main Idris repository: https://www.github.com/idris-lang/idris-dev/ 

This new version allows for generation of ePub, PDF, and HTML versions that are publicly available using [readthedocs](http://idris.readthedocs.org).

I am marking this issue as being closed.
